### ISSUE TITLE
[Scheduled Maintenance] Los servicios listados estarán en mantenimiento temporalmente.

### ISSUE THREAD

**Issue by Disruptive-IT** [jfcatano/disruptive-uptime#14]
**Additional context**
Mantenimiento general programado para realizar cambios y migraciones de todos los sistemas internos de los servidores de Disruptive.

Los siguientes servicios estarán fuera de línea durante el tiempo estimado:
- Sitio web de Disruptive.
- API de Mesadoko
- API de LAR
- Sitio web de LAR

**Comment by jfcatano** [comment]
El mantenimiento fue aumentado hasta el día de mañana para los dos servicios que aún continúan fuera de línea.

**Comment by jfcatano** [comment]
El mantenimiento y migración de servidores finalizó con éxito. Todos los servicios ya se encuentran operativos.
